#!/usr/bin/env python3
"""Live proof: run the probe suite against one or MORE real vision models and
write the evidence artifacts — out/RESULTS.md (scorecards + every raw answer)
and out/vss_results_table.tex (paste-ready multi-model Results table for the
VSS paper). Exits non-zero if nothing could be measured. Usage:

    ANTHROPIC_API_KEY=… python run_real.py [--models claude-sonnet-5,claude-haiku-4-5-20251001]

A model with no key/credits is reported "not measured" (excluded, never faked).
"""
from __future__ import annotations

import argparse
import datetime
import sys
from pathlib import Path

from probe_runner import MockVSS, gate, load_spec, run_probes, scorecard
from vlm_adapter import get_adapter

OUT = Path(__file__).parent / "out"
DEFAULT_MODELS = "claude-opus-5,claude-sonnet-5,claude-haiku-4-5-20251001"


def latex_table(baseline: dict, results: dict[str, dict]) -> str:
    models = list(results.keys())
    header = " & ".join(["Failure mode", "VSS (obs.)"] + [m.replace("claude-", "c-").replace("-20251001", "") for m in models] + ["Min"])
    rows = []
    for mode_id, b in baseline.items():
        cells = [mode_id.replace("_", " "), f"{b['score']:.2f}"]
        for m in models:
            r = results[m][mode_id]
            cells.append("n.m." if not r["measured"] else f"{r['score']:.2f}")
        cells.append(f"{b['threshold']:.2f}")
        rows.append("    " + " & ".join(cells) + r" \\")
    return (
        "% Auto-generated by FM-os skills/vlm-failure-probe/reference/run_real.py\n"
        "% Baseline column = the paper's observed VSS failures encoded as canned answers.\n"
        "% n.m. = not measured (no key/credits) — excluded, never a fake pass.\n"
        "\\begin{table*}[t]\n  \\centering\n"
        "  \\caption{Failure-mode probe scores: observed VSS baseline vs. frontier vision models.}\n"
        "  \\label{tab:probe-results}\n"
        f"  \\begin{{tabular}}{{l{'c' * (len(models) + 2)}}}\n"
        "    \\hline\n"
        f"    {header} \\\\\n"
        "    \\hline\n" + "\n".join(rows) + "\n    \\hline\n  \\end{tabular}\n\\end{table*}\n"
    )


def results_md(baseline: dict, results: dict[str, dict], spec: dict, stamp: str) -> str:
    models = list(results.keys())
    lines = [
        "# vlm-failure-probe — live multi-model run",
        "",
        f"- **models**: {', '.join(models)} · {stamp}",
        "- **stimuli**: deterministic synthetic frames (`stimuli.py`), the paper's own methodology",
        "- **baseline**: the VSS paper's observed failures, canned verbatim (`MockVSS`)",
        "- n.m. = not measured (no key/credits) — excluded, never a fake pass",
        "",
        "| failure mode | VSS baseline | " + " | ".join(models) + " | min |",
        "|---|---|" + "---|" * (len(models) + 1),
    ]
    for mode_id, b in baseline.items():
        cells = [f"| {mode_id} | {b['score']:.2f} "]
        for m in models:
            r = results[m][mode_id]
            cells.append("| n.m. " if not r["measured"] else f"| {r['score']:.2f} ")
        cells.append(f"| {b['threshold']:.2f} |")
        lines.append("".join(cells))
    lines += [""]
    for m in models:
        ok, reasons = gate(results[m], spec)
        lines.append(f"**{m} gate:** {'PASS' if ok else 'FAIL — ' + '; '.join(reasons)}")
    lines += ["", "## Raw answers (evidence)", ""]
    for m in models:
        lines.append(f"## {m}")
        for mode_id, r in results[m].items():
            lines.append(f"### {mode_id}")
            for p in r["probes"]:
                ans = p["answer"] if p["answer"] is not None else "*(not measured)*"
                sc = "—" if p["score"] is None else f"{p['score']:.2f}"
                lines.append(f"- `{p['id']}` [{sc}] {ans}")
            lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--models", default=DEFAULT_MODELS)
    args = ap.parse_args()

    spec = load_spec()
    n_probes = sum(len(m["probes"]) for m in spec["failure_modes"])
    baseline = run_probes(MockVSS(), spec)
    results: dict[str, dict] = {}
    for model in [m.strip() for m in args.models.split(",") if m.strip()]:
        print(f"probing {model} across {n_probes} probes…")
        results[model] = run_probes(get_adapter(model), spec)
        print(scorecard(model, results[model], spec))

    measured = [m for m, r in results.items() if any(v["measured"] for v in r.values())]
    if not measured:
        print("nothing measured (no keys?) — no artifacts written")
        sys.exit(1)

    stamp = datetime.date.today().isoformat()
    OUT.mkdir(exist_ok=True)
    (OUT / "RESULTS.md").write_text(results_md(baseline, results, spec, stamp))
    (OUT / "vss_results_table.tex").write_text(latex_table(baseline, results))
    print(f"wrote {OUT / 'RESULTS.md'} and {OUT / 'vss_results_table.tex'}")
