#!/usr/bin/env python3
"""
build_router.py — generate the /FM-os hub router index (progressive disclosure).

Reads the two sources of truth for "what tools exist":
  - data/registry.yml   (curated skills, with certification from data/_certifications.yml)
  - distill/manifest.json (tooling distilled from cited repos)
…extracts each tool's `description` from its SKILL.md frontmatter, and injects a routing table
between the FM-OS-ROUTER markers in skills/fm-os/SKILL.md.

Spec-as-data: /FM-os's index can never drift from the tools that actually exist — `--check` fails
CI if the generated block and the committed block differ. As `make distill` adds repos, re-running
this makes /FM-os aware of every new toolset automatically.

Usage:
    python3 scripts/build_router.py            # regenerate the router block in place
    python3 scripts/build_router.py --check    # fail (exit 1) if the block is stale
"""
from __future__ import annotations
import argparse, json, re, sys
import yaml
from fmos import ROOT, load

SKILL = ROOT / "skills" / "fm-os" / "SKILL.md"
START = "<!-- FM-OS-ROUTER:START (generated by scripts/build_router.py — do not edit by hand) -->"
END = "<!-- FM-OS-ROUTER:END -->"


def frontmatter(md_path) -> dict:
    """Parse the YAML frontmatter of a SKILL.md (between the first two `---` lines)."""
    text = md_path.read_text()
    m = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    return yaml.safe_load(m.group(1)) if m else {}


def cell(s: str, cap: int = 150) -> str:
    """One-line, pipe-safe markdown cell."""
    s = re.sub(r"\s+", " ", (s or "").strip())
    return (s[: cap - 1] + "…" if len(s) > cap else s).replace("|", "\\|")


def certifications() -> dict:
    try:
        return yaml.safe_load((ROOT / "data" / "_certifications.yml").read_text()) or {}
    except FileNotFoundError:
        return {}


def curated_rows(certs: dict) -> list[dict]:
    rows = []
    for e in load("registry"):
        if e.get("kind") != "skill":
            continue
        path = e.get("path", "")
        sk = ROOT / path / "SKILL.md"
        if e["name"] == "fm-os" or not sk.exists():   # don't list the router in its own index
            continue
        fm = frontmatter(sk)
        c = certs.get(e["name"], {})
        badge = f"✅ {c['score']}/100" if c.get("score") is not None else "—"
        rows.append({"name": e["name"], "desc": cell(fm.get("description", "")),
                     "load": f"{path}/SKILL.md", "cert": badge})
    return sorted(rows, key=lambda r: r["name"])


def distilled_rows() -> list[dict]:
    mf = ROOT / "distill" / "manifest.json"
    if not mf.exists():
        return []
    rows = []
    for it in json.loads(mf.read_text()).get("items", []):
        sk = ROOT / it["skill"]
        desc = cell(frontmatter(sk).get("description", "")) if sk.exists() else ""
        rows.append({"name": f"{it['slug']}-quickstart", "desc": desc, "load": it["skill"],
                     "repo": it.get("repo", "")})
    return sorted(rows, key=lambda r: r["name"])


def render(certs: dict) -> str:
    cur, dis = curated_rows(certs), distilled_rows()
    out = [START, "",
           f"### Certified skills ({len(cur)}) — curated, security-gated",
           "", "| Tool | What it does | Load | Certified |", "|---|---|---|---|"]
    for r in cur:
        out.append(f"| `{r['name']}` | {r['desc']} | `{r['load']}` | {r['cert']} |")
    out += ["", f"### Distilled from cited repos ({len(dis)}) — scaffolds; read upstream first",
            "", "| Tool | What it does | Load | From repo |", "|---|---|---|---|"]
    for r in dis:
        out.append(f"| `{r['name']}` | {r['desc']} | `{r['load']}` | `{r['repo']}` |")
    out += ["", f"_Total routable toolsets: {len(cur) + len(dis)}. "
            f"Regenerate with `make build`; scaled by `make distill`._", "", END]
    return "\n".join(out)


def splice(block: str) -> str:
    text = SKILL.read_text()
    return re.sub(re.escape(START) + r".*?" + re.escape(END), block, text, flags=re.DOTALL)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    block = render(certifications())
    new = splice(block)
    if args.check:
        if new != SKILL.read_text():
            print("❌ /FM-os router is STALE — run `python3 scripts/build_router.py`."); return 1
        print("OK — /FM-os router index is up to date."); return 0
    SKILL.write_text(new)
    n = new.count("| `")
    print(f"Wrote skills/fm-os/SKILL.md router ({n} tool rows).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
