#!/usr/bin/env python3
"""Weekly freshness sync — refresh live repo stats from the GitHub API.

Writes a GENERATED map to data/_stars.yml (repo -> {stars, release, pushed}).
It never rewrites the human-authored data/repos.yml, so comments and ordering
there stay intact. build_readme.py merges this map at render time.

Auth: uses $GITHUB_TOKEN if present (the Action provides it) to lift rate limits.
"""
from __future__ import annotations

import json
import os
import pathlib
import urllib.error
import urllib.request

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = DATA / "_stars.yml"
API = "https://api.github.com/repos/"


def gh(path: str):
    req = urllib.request.Request(API + path)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("User-Agent", "FM-os-sync")
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def main() -> int:
    repos = yaml.safe_load((DATA / "repos.yml").read_text()) or []
    slugs = sorted({e["repo"] for e in repos if e.get("repo")})
    result: dict[str, dict] = {}
    ok = fail = 0
    for slug in slugs:
        try:
            info = gh(slug)
            entry = {"stars": info.get("stargazers_count", 0)}
            if info.get("pushed_at"):
                entry["pushed"] = info["pushed_at"][:10]
            try:
                rel = gh(f"{slug}/releases/latest")
                if rel.get("tag_name"):
                    entry["release"] = rel["tag_name"]
            except urllib.error.HTTPError:
                pass  # many repos have no releases; that's fine
            result[slug] = entry
            ok += 1
            print(f"  ✓ {slug}: ★{entry['stars']:,}")
        except Exception as exc:  # noqa: BLE001 — log and continue, never fail the run
            fail += 1
            print(f"  ✗ {slug}: {exc}")
    OUT.write_text(
        "# GENERATED by scripts/sync.py — do not edit. repo -> live GitHub stats.\n"
        + yaml.safe_dump(result, sort_keys=True, allow_unicode=True)
    )
    print(f"Synced {ok} repos ({fail} failed) -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
